### ISSUE TITLE
MQTT Interface

### ISSUE THREAD

**Issue by Schm1tz1** [Schm1tz1/ESPressIoT#1]
MQTT Interface needs to be done. 
**Key points:**
- Publish status values in a given interval
- Subscribe to control topic for changing config values, set points etc.

**Comment by Schm1tz1** [comment]
For this: Connect to AP or run in AP-and-client-mode

**Comment by Schm1tz1** [comment]
To be added: Username/Password login. Add second call if credentials are set in config as described in API:
https://pubsubclient.knolleary.net/api.html

**Comment by VastSky** [comment]
I'll take a look at pubsubclient.

Thanks!

**Comment by Schm1tz1** [comment]
@VastSky did you make any progress here, does it work? Please share you experience so maybe I can improve my project a bit.

**Comment by VastSky** [comment]
No progress made.

**Comment by Schm1tz1** [comment]
Temperature setter and heater toggle are implemented.
