### ISSUE TITLE
non blocking oled driver...

### ISSUE THREAD

**Issue by jeanrocco** [Schm1tz1/ESPressIoT#12]
Hello, really like your code, thank's ! That's the best PID tool I found so far. 
I slightly modified the Adafruit max31865 library and example code to be non blocking ( no 10 msec after "bias on" and no 65 msec after "one shot" which starts the conversion, using millis(). )  . I replaced your sensor code with it, to read a 1000 ohms RTD... and it works great and is very precise.  It is for my Rancillio Sylvia... 
I was wondering if you ever came across a non blocking i2c Oled driver. I agree that with your web interface it is not required, he ! but just for sheer fun ... since I have the display. Incidently I really like the OTA updater, this is great feature and surprisingly easy once you know how to.

Thank's again for this amazing and instructive piece of code.

**Comment by jeanrocco** [comment]
Ok answering to my own issue, since I couldn't find any valid (to my level of understanding ...) Oled driver, so I used a spare esp8266 to subscribe to the MQTT topic  "ESPressIoT/temp" and display it on a  "U8X8_SSD1306_128X32_UNIVISION_SW_I2C u8x8(5,4);" Oled display. It only does that. In "ESPressIoT mqtt", I slowed down the MQTT publish to once a second and was able to get the Oled updated cleanly. Now I enjoy an autonomous portable  temperature display that I can put in any convenient place.

**Comment by jeanrocco** [comment]
Sorry wrong action...

**Comment by jeanrocco** [comment]
In case someone might be interested, look at https://github.com/jeanrocco/Espressiot_Fritzing

**Comment by Schm1tz1** [comment]
Very nice - thanks for sharing! Unfortunately I don't have much time for this project anymore and thus my response time is somewhat longer, sorry for that :-/.

**Comment by Schm1tz1** [comment]
Btw, did you find any non-blocking oled driver? I wonder if this is the right place because that's not really an issue with this project's code but more a general question...

**Comment by jeanrocco** [comment]
No luck, no non-blocking oled driver. Like I told you (in Github) I ended up using another ESP-8266 with a standard oled driver, so I didn’t looked that deep anyway, and as you say it is not an issue. Thank’s anyway for your answers !
jrb.

**Comment by jeanrocco** [comment]
Hello again, a short question, do you recall your P, I and D parameter
values you used for your Rancillio ?
Thank's
jrb.

**Comment by VastSky** [comment]
Hey jeanrocco, 
I will be returning home on 6 Aug and will provide the PID values then.

Ed

**Comment by jeanrocco** [comment]
Thank’s I don’t mind waiting a whole year !   :-)   !  “6 Aug”  I do that a lot since I retired !

jrb.

**Comment by VastSky** [comment]
Hey jeanrocco,

I was brewing an espresso and thought "wait a minute - I need those PID settings".

My machine is a Rancilio Silvia V3.     Ed 

EspressIoT
Target Temperature:
100.00

Threshold for adaptive PID:
1.50


normal PID:
P 
91.00

I 
0.26

D 
7950.00


adaptive PID:
P 
100.00

I 
0.00

D 
0.00

Load Config
Save Config
Reset Config to Default
Update Firmware
Tuning Threshold (Â°C):
0.20

Tuning Power (heater)
100.00

**Comment by jeanrocco** [comment]
Hello and thank's for the reply, much appreciated.

I will post in my Github, the "tune" code I'm working on to fix the UpperT
and LowerT max. values for a boiler system, like the Rancillio.

I presume you used something similar to tune your's. My coding skill is a
bit akward compared to your's, please don't laugh too loud 😁.
 Thanks again...
jrb.

**Comment by VastSky** [comment]
I have no coding skills at all. I can only read through someone code and make a change hoping that it works.

Here is what I did:

Log into the IP of the ESPressIoT and you should see its web gui. 

Choose the "Settings" button, then "Start PID Tuning Mode" button. 

Next simulate your typical brew protocol, but without any coffee in the portafilter. Allow reasonable time for the temperatures to stabilize after the brew, then repeat the simulated brew cycle for about five cycles. Refer to the ESPressIoT web gui for prompts on the progress of the tuning. 

Save the ESPressIoT the resulting PID values that autotune created. 

I track the tuning values by copy and pasting the ESPressIoT web gui text, and then pasting this into Excel to keep track of the PID values and the effect it had on temperature stability. This can help you to adjust PID values without running the PID Tuning Mode.

The the fact my machine is a single boiler makes it very difficult to control it to a constant stable temperature during brewing, but ESPressIoT makes it better than the stock thermal control switch.

Do you have a MQTT server for your clever MQTT remote display? I am hoping there is a way to have two ESP devices relay MQTT without using a sever to do this.

I can provide my email so we don't clog Github with our chatter - let me know!

Ed

**Comment by Schm1tz1** [comment]
Thanks for your contribtion even though this issue is not the best place for others to find such PID details and hints ;-). I will put a file with these parameters into the base directory.
