### ISSUE TITLE
No PID control if there is no network connection

### ISSUE THREAD

**Issue by ThomasPu89** [Schm1tz1/ESPressIoT#13]
Hello,

is it possible that the ESPressIoT does not work without network Connection?

When I plug in my wlan repeater everything seems ok.

I think thats based on:

  void setup(){
...
while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
}

If am right, can we implement a fallback solution like:

void setup(){
...
for (int i = 0; i <= 120 && WiFi.status() != WL_CONNECTED ; i++)
        delay(500);
        Serial.print("."); 
}

Best regards and thanks for that amazing peace of software
Thomas

**Comment by Schm1tz1** [comment]
Hi, thanks for your message, you are absolutely correct. This is kind of "historical" code as I originally implemented it as a WIFI AP that you can connect to with your phone. Maybe one can even go back to a smaller count of repetitions. In case you need ~100 reconnects, there is something wrong anyway. I will update that soon.

**Comment by Schm1tz1** [comment]
Done. Btw, in case of such proposed changes you can also do a pull request.
