### ISSUE TITLE
Tuning loop not doing correct Peak-To-Peak-Temperature

### ISSUE THREAD

**Issue by Schm1tz1** [Schm1tz1/ESPressIoT#2]
For peak-to-peak values the difference between upper and lower averages out of N measurements is calculated. These averages are calculated taking the first temperature after crossing a threshold. This if of course not correct as in a system with a nonvanishing heat capacity (e.g. 100ml of water) the response to the heating will be delayed and thus we have over- and undershoot in our tuning loop.
Here some simple peak-detection needs to be done. Maybe a ring-buffer with a few values of "temperature-history" or some min/max-detection after crossing a threshold comparing each value to a stored min/max will be fine...

**Comment by jeanrocco** [comment]
Hello Roman, I added some code to fix this issue, you could look in https://github.com/jeanrocco/Espressiot_Fritzing/tree/master/espressiotJR3b7c if you ever feel like it. 
best regards,
jrb

**Comment by Schm1tz1** [comment]
Did you run into this issue again? For my case it was solved an 2017-07-01.

**Comment by jeanrocco** [comment]
Hello, it was not getting the "peak" temperatures... hence my code.
Where or how was it solved in 2017-07-01 ?
