### ISSUE TITLE
Enable for AWS-IoT

### ISSUE THREAD

**Issue by Schm1tz1** [Schm1tz1/ESPressIoT#9]
MQTT via pub-sub is working fine, a connection via AWS-IoT would be perfect.

**Comment by VastSky** [comment]
Roman, 

I wish to sincerely thank you for sharing EspressIoT and cofcon. These two projects have provided me with enough Arduino code to build and deploy PID on my Rancilio Miss Silvia. I have been hoping add PID to my machine for many years but did not like the solutions available until I found yours. I used a Wemos D1 mini, SSR, and a DS18b20 (I had this sensor on hand, and never need steaming temperatures). 

I am not able to code in Arduino, but did manage to succeed in porting your DS18b20 example from cofcon into EspressIoT so I could proceed with installing the hardware in to my machine. 

Tonight I got MQTT working. You can't imagine how pleased I am with your code!! Next I will try to figure out OTA.

Best Wishes - Happy New Year - Ed Rilkoff - Kamloops BC Canada

**Comment by Schm1tz1** [comment]
Cool, nice to hear that it is working for you.
Happy new year and have fun !

**Comment by Schm1tz1** [comment]
Obsolete.
